import { Inter } from "next/font/google";
import Navbar from "./components/navbar.js";
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import AddBootstrap from "./addbootstrap";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AddBootstrap/>
      <Navbar/>
        {children}
        

        </body>
    </html>
  );
}
