import { Inter } from "next/font/google";
import Navbar from "./components/navbar.js";
import style from './globals.css'
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.body}>
      <Navbar/>
        {children}      
        </body>
    </html>
  );
}
